### ISSUE TITLE
Should all line based checks ignore multiline strings?

### ISSUE THREAD

**Issue by adireddy** [adireddy/haxe-checkstyle#191]
Can't decide myself so posting here for some feedback.

**Comment by adireddy** [comment]
I have added `ignorePattern` for the above checks so meta data like `@desc` or comments `\\` can be ignored.

**Comment by AlexHaxe** [comment]
I think that is something we need to decide on a per check basis:
- `TrailingWhitespace`, `IndentationCharacter`, `EmptyLines`, `TODOComment` and `TabForAlignment` should not trigger a message when inside a string, because we cannot tell developers what strings to use
- `FileLength` does not apply, if your file is too long, it's too long
- `LineLength` should always trigger a message (in my opinion), if your string is too long, then either break it up using `+` or put it into an external ressoure. There is probably some macro based mechanism available, so it comes with no runtime costs.

**Comment by Gama11** [comment]
Yeah, `FileLength` is definitely an exception here. Not entirely sure about `LineLength`, but I can see why you would want to warn anyway. I agree with @AlexHaxe that all the other ones shouldn't give any warnings if within strings.

**Comment by adireddy** [comment]
:+1:
