### ISSUE TITLE
Duplicate checks: line length

### ISSUE THREAD

**Issue by alebianco** [adireddy/haxe-checkstyle#25]
LeftCurly does the same job as LineLength by checking the length of the line.
It would be better to remove that and only check for the position to keep things isolated.

**Comment by AlexHaxe** [comment]
Yes, LeftCurly has a maxLineLength check, but it only checks line length when set to EOL – enforces left curly placement before maxLineLength (which might be lower than LineLengthCheck's value). 

I have tried to mimic the Java implementation of LeftCurly (http://checkstyle.sourceforge.net/config_blocks.html#LeftCurly), that's why it has a maxLineLength parameter. 

The current implementation of maxLineLength would fire an error message, when a line is longer than maxLineLength, but if you fix it by putting left curly on a new line, it would fire an error message, because it is on a newline and not EOL. So right now there is no real fix for such an error, probably also caused by a lack of the nlow option (= newline on wrap).

**Comment by adireddy** [comment]
Hey @AlexHaxe, Just noticed that checksyle deprecated `maxLineLength` property http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/blocks/LeftCurlyCheck.html

I am inclined to remove this property as it's definitely prone to confusion.

Check the discussion here https://github.com/checkstyle/checkstyle/issues/965

**Comment by AlexHaxe** [comment]
I agree, I have not seen it fire on any of my code (but I use newline mode).

LineLengthCheck is probably enough for most / all use cases, so we can safely drop it from LeftCurlyCheck.

**Comment by adireddy** [comment]
:+1: I will update the check.
