### ISSUE TITLE
Multiline detection in LineCheckBase is buggy

### ISSUE THREAD

**Issue by francoisvn** [adireddy/haxe-checkstyle#278]
Multiline detection in LineCheckBase is prone to bugs. Including a quote in a comment will result in the rest of the file being ignored, which is clearly not correct.

Test that should pass, but fails: https://github.com/HaxeCheckstyle/haxe-checkstyle/pull/277/commits/543846f97b54d5c35847776a83b3dd2e0a456bb7

Using regular expressions to detect and ignore some checks inside strings seems like a challenge not worth trying to fight.

**Comment by Gama11** [comment]
I just ran into this... `'` is extremely common in Flixel's doc comments, so the indentation character check is broken basically everywhere.

> Using regular expressions to detect and ignore some checks inside strings seems like a challenge not worth trying to fight.

I don't know, that would make using multiline strings together with checkstyle a huge pain... And checkstyle uses them all over the place in its tests.

**Comment by AlexHaxe** [comment]
I think there are two ways to fix the problem:
1. pattern matching: add detection for comments and escaped quotation marks
2. go hybrid: use token tree to locate comments and strings

**Comment by seraku24** [comment]
Doing a quick code review, the logic within the (curiously misspelled) function `isMultineString()` appears to me to simply be incorrect on detecting the start and end of strings.  For instance, the presence of any escaped quotes in a line would prevent the proper closing of a multi-line string, which doesn't make sense.  In fact, the regex for finding a quote should include the escaping logic within it: `(?<!\\)['"]`, for example.  This would match either a single or double quote that is _not_ preceded by a backslash.  Of course, there still needs to be added logic to ensure this quoted string is not within the scope of a line or block comment.

Additionally, `IndentationCharacterCheck` is not even using the function properly.  In order for the base class to maintain its tracking of multi-line strings, it needs to be invoked for every line regardless of what the derived check does with the lines.  As it stands, a line suppression would result in the state becoming invalid due to skipping over lines that might contain the start or end of a string.  I have only done a spot check on a few other derived classes, and most seem to be calling the base function in the correct location, but it would be worth reviewing the other checks to ensure proper usage of the function.

If I get some time between projects, I will fork this project and try my hand at updating the multi-line string logic.  Hopefully, this project is easy to build and test.  `(:`

**Comment by adireddy** [comment]
Like @AlexHaxe said, I think using token tree will be a better & reliable solution.

@seraku24 if you can spare time, please go ahead and review/modify the current logic.
