### ISSUE TITLE
Support Haxe 4 "in" Binop

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#352]
see https://github.com/HaxeCheckstyle/haxe-checkstyle/pull/351#issuecomment-323786703

**Comment by Gama11** [comment]
@AlexHaxe Did you mean to close this with https://github.com/HaxeCheckstyle/haxe-checkstyle/pull/359?

**Comment by AlexHaxe** [comment]
well, it's fixed from our side...
mcover accepted my pull request, but so far no haxelib release
haxeparser has support for it in git version, but also no haxelib release (and it lacks arrow function support, which I looked into porting myself, but quickly gave up)
That's why I set it to waiting, also the development build is still red.

I must admit I haven't asked for new releases of these libraries, which means it will probably stay on waiting indefinitely...

**Comment by AlexHaxe** [comment]
I think `Binop(OpIn)` support has been in haxeparser (git) for some time. Do we need to fix anything else on our side?

**Comment by Gama11** [comment]
This is a pretty old issue that I don't even really remember opening, but... probably not? :)
