### ISSUE TITLE
Exit code

### ISSUE THREAD

**Issue by RealyUniqueName** [adireddy/haxe-checkstyle#36]
Could please add proper exit codes if any issues spotted?
Right now i have to parse report to find out if checks didn't pass.

**Comment by AlexHaxe** [comment]
I have added a new command line option `-exitcode` that will set the exit code to the number of failed checks (currently only in `dev` and `token-tree` branches).

It's not on by default, because most CI systems (like Jenkins, Hudson, Travis, etc.) will fail a build if a build step returns a non zero value.
