### ISSUE TITLE
Combine JSON config with default.json

### ISSUE THREAD

**Issue by Starmann** [adireddy/haxe-checkstyle#401]
When creating a checkstyle.json file, it overrides the default.json rather than merging with it. This is inconvenient because it requires the user to copy the default.config which may cause some confusion for users.

**Comment by AlexHaxe** [comment]
I am not sure I can follow. Do you want to be able to specify two config files when running checkstyle?

Using `--default-config <filename>` generates a default checkstyle config, which contains every check available with its default settings. I guess that's what you are referring to as `default.json`.  Running checkstyle with `default.json` is the same as running checkstyle without `-c <configfile>` parameter. It is meant as a starting point, giving you a file that has the correct format and comes with every check and every property, so you can go in and remove checks or change properties, to see how it affects your checkstyle results.
If you are happy with checkstyle's defaults you don't even have to set all properties, you can just list the checks you want to run, e.g.:
```
:
{
    "type": "ArrayLiteral"
},
{
    "type": "AvoidStarImport"
},
:
```

Starting with checkstyling your code can be a lot of work, because initially there might be hundreds or thousands of checkstyle issues in your code (depending on number of files / lines of code). Many of them will go away once you start customising your checkstyle configuration, teaching checkstyle your coding style. 

That being said, running your custom config along with `default.json` doesn't make much sense, because checks will run multiple times if they occur more than once in your config. 
e.g. `TypeName` check, you might want to have all interfaces start with `I`, whereas every other type should have a different name pattern, so you put in two instances of `TypeName` check, one for interfaces one for all other types.
Merging `default.json` would mean running all checks in default configuration on top of your custom config.

**Comment by Starmann** [comment]
Apologies. I'm not very good at communicating.

When you run Checkstyle and there isn't a checkfile.json in the current directory, it uses the default config (resources/default.json).

Now suppose you add a simple checkstyle.json file to the current directory.

```json
{
    "checks":
    [
        {
            "type": "AvoidStarImport",
            "severity": "IGNORE"
        }
    ]
}
```
Result:
The config options not specified in the checkstyle.json are ignored
Expected:
It should inherit the options from checkstyle.json

**Comment by AlexHaxe** [comment]
With no `checkstyle.json` checkstyle uses its internal default settings, which are identical to  what you see in `resources/default-config.json`, but the actual file is not needed or read during a run. It is simply the output of `--default-config <filename>`.

Inheriting all default checks when all you provide is a minimal `checkstyle.json` is probably worse than what we have now:
- If all you want is to run a handful of checks, then you would have to add all checks you don't want to run, just to disable them. Even checkstyle does not use all checks, other projects use a selected subset.
- Some checks may appear multiple times in a configuration, so having multiple instances of the same check is not uncommon for checkstyle, but inheriting default checks means we would have to keep track where checks come from.
- Also not everyone shares checkstyles coding style, so many people will have to make a lot of changes to the default settings anyway.

If the default config of checkstyle is what you want, then run checkstyle with `--default-config <filename>`, and generate your base configuration, and then edit it to change the bits where your coding style deviates. You only have to do it once, of course if checkstyle adds new checks or new options you might have to revisit your settings, but at least using `-show-missing-checks` will list all checks that you currently don't use.

**Comment by Starmann** [comment]
Woops. I guess I forgot about compatibility issues that it might cause. Eslint has an option that I believe makes for a nice compromise:
```json
{
    "extends": "eslint/recommended"
}
```

**Comment by AlexHaxe** [comment]
I can see it as a way to have one central configuration file and then for each project you can have a local file that just points to it / extends from it. Especially when you have multiple projects it can be a challenge to sync your checkstyle configuration to every project folder. 
Having a centralised version from which you can extend might help in that situation.
