### ISSUE TITLE
token-tree branch

### ISSUE THREAD

**Issue by adireddy** [adireddy/haxe-checkstyle#51]
@AlexHaxe Just creating this to keep track of changes in token-tree branch

I am thinking of releasing v2 will all the new checks and features from token-tree branch.

Please prepare release notes highlighting breaking changes if any and let me know whenever you want to release it.

Post all the details here for tracking until we release it.

**Comment by AlexHaxe** [comment]
In a first step towards v2, I have added a `LIMITATIONS.md` to the token-tree branch listing the pros and cons of the different check types used in checkstyle. We might have to compile a list of which check belongs to what type, so it becomes clear where those limitations apply.

**Comment by Gama11** [comment]
The part about

> no support for #if, #else, #elseif, etc.

is a bit misleading in my opinion. They are _supported_, but due to the nature of conditionals, only the code that made it through the currently active ones can actually be checked.

I think checkstyle needs to expose an API for running AST-based checks several times with different combinations of defines to mitigate this.

**Comment by AlexHaxe** [comment]
After looking through haxeparser again, I have changed the wording a bit. 

Providing an API for conditionals is probably the best solution for AST based checks. It might even make sense add this to token tree checks, it will definitely make things easier.
We would have to find a way to eliminate duplicate test results, because findings are not limited to conditional areas on consecutive runs.

**Comment by AlexHaxe** [comment]
In your comment https://github.com/adireddy/haxe-checkstyle/pull/91#issuecomment-191317247 you were asking for merging of tokenizer bugfixes. I have been thinking about it, and most of the changes to token tree branch have been bugfixes with a few new checks thrown in now and then. And I have converted three checks to token tree. 

The main reason I am holding back on merging to dev is the tree builder, because might stacktrace or end up in an endless loop. I am not so concerned about the new checks, although they are the ones that will fail because of unsupported token combinations handled incorrectly by token tree builder.

Since we now have a way to handle failures or broken checks and since users can disable a broken check, I think we should consider merging both branches.
If we get lots of people complaining about broken checks (especially the three checks that were refactored to token tree), we can either fix them or provide the old versions alongside the new ones until they are fixed.

Or is there a show stopper, that should be addressed before merging?

**Comment by AlexHaxe** [comment]
release notes:
- implemented a tree tokenizer, adding a new class of checks based on tokens and their relationship
  - tree tokenizer arranges all tokens into a tree structure
  - all tree nodes have the same type with position info
  - easy traversal of token tree
  - access to parent token
- added EmptyBlock, OperatorWrap, SeparatorWrap, WhitespaceAfter and WhitespaceAround checks
- refactored LeftCurly, RightCurly and NeedBraces checks to use token tree
- moved block and whitespace checks into separate packages
- removed BlockFormat check -> use LeftCurly, RightCurly and EmptyBlock instead

possible issues:
- unhandled combinations of tokens can result in endless loops or stacktraces in checks using token-tree
  - temporary solution -> disable check in config
  - open an issue with sample code

**Comment by Gama11** [comment]
I think the sooner it gets merged, the better. There's quite a bit of overhead to managing multiple branches.

**Comment by adireddy** [comment]
Ok then, let me do the folder changes in token tree branch and then you can raise a pull request.

**Comment by adireddy** [comment]
Ok @AlexHaxe I am done with the changes in token tree branch.
