### ISSUE TITLE
WhitespaceAround fails on interface with implements

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#80]
``` haxe
interface Test implements Dynamic {}
```

```
./source/Test.hx:1: character 0 : Error: Check WhitespaceAfter failed: bad token Kwd(KwdImplements) != BrOpen
```

**Comment by AlexHaxe** [comment]
`interface Test extends Dynamic {}`

**Comment by AlexHaxe** [comment]
Haxe docs say it should be extends and I usually use extends for interfaces, but it seems implements throws no compile error, so I added support for it to tree tokenizer.

**Comment by Gama11** [comment]
This example was from the standard library: https://github.com/HaxeFoundation/haxe/blob/3.2.0/std/haxe/remoting/AsyncConnection.hx#L24

**Comment by AlexHaxe** [comment]
I grepped through my haxelib folder and found a few cases, though the majority used extends. I guess at some point it was changed, but the old way is still supported.
It makes sense to not have token tree checks break because of that. 

However we could write a check to enforce extends over implements for interfaces.
