### ISSUE TITLE
Add a check for empty comments / JavaDoc tags

### ISSUE THREAD

**Issue by Gama11** [adireddy/haxe-checkstyle#87]
I dislike having auto-generated, empty doc comments like this:

``` haxe
/**
 * 
 * @param   arg
 * @param   pos
 */
```

**Comment by AlexHaxe** [comment]
This can either be done by a line based or a token tree based check, AST based checks throw away comments (mainly because there is no node in AST for comments).

I guess for this particular check a line based version would suffice. 
If you want to go a step further and check if the `@params` match the function parameters then you would have to go token tree or have a more complex set of parsing and regex rules for a line based check.
